import Layout from "components/layout";
import { NextPageWithLayout } from "interface";
import Head from "next/head";

const Contact: NextPageWithLayout = () => {
  return (
    <div>
      <Head>
        <title>Contact Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>AAAAAAAAAAAAAAAAAAaa</main>
      <footer></footer>
    </div>
  );
};

Contact.getLayout = (page) => <Layout>{page}</Layout>;

export default Contact;
