import Layout from "components/layout";
import { NextPageWithLayout } from "interface";
import Head from "next/head";
import styles from "styles/Home.module.css";

export const Home: NextPageWithLayout = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Shop App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}></main>
      <footer className={styles.footer}></footer>
    </div>
  );
};

Home.getLayout = (page) => <Layout>{page}</Layout>;
export default Home;
